# Generated by Django 4.1 on 2022-08-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estadoAtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIVEL', models.CharField(choices=[('1', 'RECEIVED'), ('2', 'CONFIRMED'), ('3', 'DISPATCHED'), ('4', 'DELIVERED'), ('5', 'CANCELED')], default='4', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
                ('produto', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=6)),
                ('entregue', models.BooleanField()),
                ('estado', models.CharField(max_length=10)),
                ('Timestamp', models.DateTimeField()),
            ],
        ),
    ]
