# Generated by Django 4.1 on 2022-08-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoatual',
            old_name='NIVEL',
            new_name='nivel',
        ),
        migrations.AddField(
            model_name='estadoatual',
            name='descricao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
